CHANGELOG, cli_helpers/tabular_output/vertical_table_adapter.py, tests/tabular_output/test_vertical_table_adapter.py
This makes the vertical table output more customizable. Specifically:
- You can specify the left and right separator length (e.g. `--[ TITLE] --------`).
- You can better control the title, e.g. `'TITLE {n}'` would put the record count after the title.
=> Make vertical table separator more customizable.

CHANGELOG, cli_helpers/tabular_output/output_formatter.py, cli_helpers/utils.py, tests/tabular_output/test_output_formatter.py
This adds a `preprocessors` argument to `TabularOutputFormatter.format_output()`. This is used to pass additional preprocessors that should be run when formatting the output.
Additional preprocessors are run before the default preprocessors for a formatter. Preprocessors are also de-duped so that each preprocessor is only run once.
This can be used to always run the `missing_value` preprocessor for pgcli/mycli so that missing values that contain color codes will not affect the alignment in tabulate: https://github.com/dbcli/pgcli/commit/4f7add55421574ebcba3ceb5dce17c98a377a9df
=> Add preprocessors argument to format_output().

CHANGELOG, cli_helpers/tabular_output/tabulate_adapter.py, tests/tabular_output/test_output_formatter.py, tests/utils.py
Tabulate doesn't do well when the default value has ANSI escape codes in it (e.g. https://github.com/dbcli/pgcli/commit/4f7add55421574ebcba3ceb5dce17c98a377a9df). This is needed to match pgcli's behavior.
This uses the `override_missing_value` preprocessor to get around that. Tabulate can handle ANSI escape codes in the data rows themselves.
=> Use override_missing_value for tabulate.

.travis.yml, CHANGELOG, cli_helpers/compat.py, cli_helpers/tabular_output/preprocessors.py, cli_helpers/tabular_output/tabulate_adapter.py, cli_helpers/tabular_output/terminaltables_adapter.py, cli_helpers/tabular_output/vertical_table_adapter.py, docs/source/index.rst, setup.py, tests/tabular_output/test_preprocessors.py, tox.ini
This adds styled output (headers, odd row, and even row) powered by Pygments. This provides foreground colors, background colors, and bold/underline/italics.
This is an optional CLI Helpers feature that is enabled if Pygments is installed. Since this isn't required to make the essential pieces of CLI Helpers work, it's optional. I think that's a good policy to take since CLI Helpers is designed to be used by other applications outside of dbcli. It can be required downstream (e.g. mycli and pgcli) by using the setuptools extras syntax. For example, in mycli we might change the CLI Helpers dependency from `cli_helpers` to `cli_helpers[styles]`.
It requires a Pygments style class to be passed in that will respond to the desired tokens (defaults to `Token.Output.Header`, …
=> Add styled output.

.travis.yml, .travis/install.sh, CHANGELOG, setup.cfg
This adds macOS tests to the Travis config. The upcoming config pull request has mac-specific code that will be useful to test in Travis (i.e. finding Mac-appropriate config file locations when the client app explicitly does not want to follow the XDG spec).
Travis does not have built-in support for testing Python apps on macOS, so this uses a [cryptography-influenced](https://github.com/pyca/cryptography/blob/master/.travis/install.sh) `.travis/install.sh` bash script to set up Python on macOS.
=> Add macOS tests via Travis

CHANGELOG, cli_helpers/compat.py, cli_helpers/tabular_output/delimited_output_adapter.py, cli_helpers/tabular_output/preprocessors.py, setup.py, tests/tabular_output/test_delimited_output_adapter.py, tests/tabular_output/test_preprocessors.py
This fixes two unicode issues in CLI Helpers.
1. On Python 2, we now use `io.StringIO` instead of `StringIO.StringIO`. The `io` package apparently has the same behavior as Python 3.
2. We use [`backports.csv`](https://github.com/ryanhiebert/backports.csv) for Python 2's csv writing since it has the same API as Python 3's `csv` module.
Also, adds unicode tests for styling output and writing to CSV.
This addresses #18.
=> Fix unicode problems

CHANGELOG, cli_helpers/compat.py, cli_helpers/tabular_output/output_formatter.py
If the number of columns in the data is uneven, CLI Helpers raises an `IndexError`. This fixes that by using `itertools.zip_longest` when calculating column types.
This fixes https://github.com/dbcli/pgcli/issues/749.
=> Use itertools to get column types.

CHANGELOG, cli_helpers/compat.py, cli_helpers/tabular_output/delimited_output_adapter.py, cli_helpers/tabular_output/preprocessors.py, tests/tabular_output/test_preprocessors.py
Python 2 has three versions of `StringIO`:
1. `cStringIO.StringIO` (bytes-only)
2. `io.StringIO` (unicode-only)
3. `StringIO.StringIO` (unicode and 8-bit strings).
We've already tried using the first two, here's to the third 🍺 .
On Python 2, if a row has a newline in it, Pygments does some extra handling for styled output. It outputs a newline (in bytes), which `io.StringIO` cannot handle.
This addresses https://github.com/dbcli/mycli/issues/479.
=> Fix python2 styling with newlines

CHANGELOG, cli_helpers/tabular_output/delimited_output_adapter.py, cli_helpers/tabular_output/tabulate_adapter.py, cli_helpers/tabular_output/terminaltables_adapter.py, cli_helpers/tabular_output/vertical_table_adapter.py, tests/tabular_output/test_delimited_output_adapter.py, tests/tabular_output/test_output_formatter.py, tests/tabular_output/test_tabulate_adapter.py, tests/tabular_output/test_terminaltables_adapter.py, tests/tabular_output/test_vertical_table_adapter.py
=> output generator

AUTHORS, CHANGELOG, setup.cfg, setup.py
Fixed by Terje Røsten
https://bugzilla.redhat.com/attachment.cgi?id=1314388&action=diff
The rationale behind not installing backports.csv for Python 3 is that it isn't available for Fedora.
=> Use backports.csv only for py2

.travis.yml
Travis CI does not appear to support tests on macOS using Python 2.7 any longer. The CLI Helpers tests have been failing for quite awhile because of this. This fixes the failing test suite by removing that environment from the travis config file.
=> Do not test travis macOS py27.

CHANGELOG, requirements-dev.txt, tests/test_utils.py
Use a safe float for the unit tests
=> use safe float (2578310786669609 / pow(2, 50) == 2.29)

CHANGELOG, requirements-dev.txt, setup.py, tox.ini
- Updates twine
- Uses `twine check` since `python setup.py check -r` is deprecated.
- Builds the source distribution in the packaging tests (so twine can check the description in it).
- Adds the [missing content type metadata](https://packaging.python.org/guides/making-a-pypi-friendly-readme/).
=> Update version of twine and use twine check.

CHANGELOG, cli_helpers/tabular_output/delimited_output_adapter.py, cli_helpers/tabular_output/output_formatter.py, cli_helpers/tabular_output/tsv_output_adapter.py, cli_helpers/utils.py, tests/tabular_output/test_delimited_output_adapter.py, tests/tabular_output/test_tsv_output_adapter.py
Rename old tsv format to csv-tab (because it add quotes), introduce new tsv output adapter.
More information about tsv: 
https://en.wikipedia.org/wiki/Tab-separated_values
(links to: https://www.iana.org/assignments/media-types/text/tab-separated-values)
=> rename tsv to csv-tab, add new tsv output adapter

CHANGELOG, cli_helpers/tabular_output/output_formatter.py, cli_helpers/tabular_output/preprocessors.py, cli_helpers/tabular_output/tabulate_adapter.py, cli_helpers/tabular_output/terminaltables_adapter.py, cli_helpers/utils.py, tests/test_utils.py
Attempt to fix https://github.com/dbcli/pgcli/issues/976. This is a pretty crude approach of "Who in the world wants to see more than ~5000~ 500 characters in one field in a tabular display? Nobody. Let's truncate it, otherwise tabulate is going to choke." It is open to suggestions.
Note that this line in `pgcli`:
https://github.com/dbcli/pgcli/blob/7b03f8e2043682aa2d1c06e0f7e8258b2f9c43c5/pgcli/main.py#L1200
does not handle the problem, since 1) the check only happens if `auto_expand` is set, and 2) the check happens after formatting, and formatting taking forever is the actual issue.
=> Truncate very large fields for tabular display.

CHANGELOG, cli_helpers/tabular_output/output_formatter.py, cli_helpers/tabular_output/tabulate_adapter.py, cli_helpers/tabular_output/terminaltables_adapter.py
Completions weren't shown after the \T command because they weren't unicode.
=> Return the supported formats as a list of unicode strings.

AUTHORS, CHANGELOG, cli_helpers/tabular_output/preprocessors.py, cli_helpers/tabular_output/terminaltables_adapter.py, tests/tabular_output/test_preprocessors.py
If data contain `tab`, the table output format looks weird. For example:
```
+-----------------------+
| tables                |
+-----------------------+
| CREATE TABLE aaa (    |
| 	bbb varchar not null |
+-----------------------+
```
It's because table formatter treats a tab as a normal character while the terminal treats it in a different way (e.g. 4 or 8 spaces wide).
``` python
from cli_helpers.tabular_output import TabularOutputFormatter
table = [["CREATE TABLE aaa ("], ["\tbbb varchar not null"]]
headers = ["tables"]
def format_table(table, headers, formatter):
for i in formatter.format_output(table, headers):
print(i)
formatter = TabularOutputFormatter('ascii')
format_table(table, headers, formatter)
```
We can override `tab` with 4 spaces, `\t` or `↹`:
``` …
```
=> Override tab with 4 spaces for terminal tables.

.travis.yml, CHANGELOG, appveyor.yml, cli_helpers/tabular_output/preprocessors.py, requirements-dev.txt, setup.py, tests/tabular_output/test_preprocessors.py, tests/tabular_output/test_tabulate_adapter.py, tests/tabular_output/test_terminaltables_adapter.py, tox.ini
Pygments 2.4.0 included a change to the ANSI color names that are recognized. Some of our tox environments in Travis CI were using 2.4.0 and others were using 2.3.1, which led to some tests failing, but not all.
This fixes that by switching to the 2.4.0 color name formats and pinning the version in requirements-dev.txt.
**Note:** This also drops Python 3.4 from the test suite and Trove classifiers since 3.4 doesn't support Pygments 2.4.0. It was end-of-lifed in March 2019.
=> Pin to Pygments >= 2.4.0 for tests and drop Python 3.4.

AUTHORS, cli_helpers/config.py, cli_helpers/tabular_output/output_formatter.py, cli_helpers/utils.py, tasks.py
Fix deprecation warning regarding invalid escape sequences in Python 3.7 . Fix done using https://github.com/asottile/pyupgrade
```
find . -iname '*.py' | grep -Ev 'example|utl|samples|deps' | xargs -P 4 -I{} python3.8 -Wall -m py_compile {} 
./tasks.py:51: DeprecationWarning: invalid escape sequence \g
'\g<option>' if active else '', cmd)
./cli_helpers/tabular_output/output_formatter.py:124: DeprecationWarning: invalid escape sequence \*
"""Format the headers and data using a specific formatter.
./cli_helpers/tabular_output/output_formatter.py:182: DeprecationWarning: invalid escape sequence \*
"""Format output using *format_name*.
./cli_helpers/utils.py:58: DeprecationWarning: invalid escape sequence \[
_ansi_re = re.compile('\033\[((?:\d|;)*)([a-zA-Z])')
./cli_helpers/config.py:194: …
```
=> Fix deprecation warning regarding invalid escape sequences.

AUTHORS, CHANGELOG, requirements-dev.txt, tests/test_config.py
Now that cli_helpers no longer support Python 2, there is no point
in using the external mock package.  Use built-in unittest.mock module
instead.
This is a really trivial change, certainly not copyrightable, so I doubt my name is worth adding there. If you think otherwise, please let me know.
=> Use built-in unittest.mock module

cli_helpers/tabular_output/preprocessors.py, cli_helpers/utils.py
I did some profiling (prompted by [a mycli issue](https://github.com/dbcli/mycli/issues/873)) and found that during output styling, we spend most of the time recreating the Pygments formatter: 
A simple caching gives a noticeable speedup. For example, on [this sample database](https://github.com/datacharmer/test_db) with `ascii` formatter `SELECT * FROM employees LIMIT 40` takes 0.969s before and 0.019s after this change (51x).
=> Optimizations in output styling

AUTHORS, CHANGELOG, CONTRIBUTING.rst, cli_helpers/tabular_output/tabulate_adapter.py, docs/source/quickstart.rst, tests/tabular_output/test_tabulate_adapter.py
Added a new table format to match psql's `\pset linestyle unicode`, as requested in https://github.com/dbcli/pgcli/issues/1029.
It is similar to the `double` format, so we could call it `single` for consistency, but I think `psql_unicode` is clearer.
I've also added a separate commit with a couple small improvements to CONTRIBUTING.rst (which btw is very well written and helpful -- thanks!)
=> Add psql_unicode table format

CHANGELOG, cli_helpers/tabular_output/tabulate_adapter.py, docs/source/quickstart.rst, tests/tabular_output/test_output_formatter.py
By popular demand https://github.com/dbcli/mycli/issues/872
=> Add 'minimal' format: the same as 'plain', but without column headers.

AUTHORS, CHANGELOG, cli_helpers/compat.py, cli_helpers/tabular_output/preprocessors.py, cli_helpers/tabular_output/tabulate_adapter.py, cli_helpers/utils.py, tests/tabular_output/test_output_formatter.py, tests/tabular_output/test_preprocessors.py
Fixes https://github.com/dbcli/pgcli/issues/1303
and allows to un-pin `pygments`
I did a quick manual test with pgcli+pygments=2.11.2 and it no longer throws an error, but I would appreciate if someone could re-check.
=> fix table_separator_token passed as string

AUTHORS, CHANGELOG, cli_helpers/tabular_output/tabulate_adapter.py, tests/tabular_output/test_output_formatter.py
Don't backslash-escape newlines, etc. in `ascii` tables, and add an `ascii_escaped` table format for users who want that behavior.
After the discussion in https://github.com/dbcli/mycli/issues/1085 , I'm convinced that if `ascii` is the recommended format in `~/.myclirc` then that format shouldn't escape newlines.  Escaping doesn't seem like what the beginning user would want or understand.  The advanced user knows how to change the setting in the config file.
@pasenor this partially reverts #60 so I don't want to go farther without your approval.  An `ascii_escaped` format was added, so it's not a revert in functionality, only defaults.  Other `*_escaped` formats could be added.
Another option would be to add an `ascii_unescaped`, leave `ascii` unchanged, and change the default in the …
=> Don't backslash-escape newlines, etc. in `ascii` tables, and add `ascii_escaped` table format

AUTHORS, CHANGELOG, cli_helpers/tabular_output/preprocessors.py, tests/tabular_output/test_preprocessors.py
Added `format_timestamps()` to preprocessors.
This allows for per-column formatting for date, time, or datetime like data.
Add a `column_date_formats` section to your config file with separate lines for each column that you'd like to specify a format using `name=format`. Use standard Python strftime formatting strings.
This works with a related pgcli PR to address my enhancement request https://github.com/dbcli/pgcli/issues/1402
=> Add `format_timestamps` preprocessor

CHANGELOG, cli_helpers/tabular_output/delimited_output_adapter.py, cli_helpers/tabular_output/tsv_output_adapter.py, tests/tabular_output/test_delimited_output_adapter.py, tests/tabular_output/test_tsv_output_adapter.py
Add headerless variants of existing CSV and TSV formats
* `csv-noheader`
* `csv-tab-noheader`
* `tsv_noheader`
Some formats seem to use dashes whereas other formats use underscores.  Underscores should probably be preferred, and even better would be to accept both.
=> Add headerless variants of CSV and TSV formats

CHANGELOG, cli_helpers/tabular_output/json_output_adapter.py, tests/tabular_output/test_json_output_adapter.py
Add two JSON-based output formats
* `jsonl`: JSONlines format: in which each row is represented on a line as a JSON object, with the column names recapitulated on every line as the property names.
* `jsonl_escaped`: like `jsonl`, except that JSON escaping is applied for non-ASCII characters.
Most users will want `jsonl`.  The implementation file has the generic name `json_output_adapter.py` in case other JSONish forms are desired.
This output format can be combined with jq redirection in mycli:
* https://github.com/dbcli/mycli/pull/1248
=> Add two JSON-based output formats

CHANGELOG, cli_helpers/tabular_output/json_output_adapter.py, cli_helpers/tabular_output/output_formatter.py, tests/tabular_output/test_json_output_adapter.py, tests/tabular_output/test_output_formatter.py
* formats must be _registered_, or they aren't available for use in client software
* make JSON formats able to encode Decimal values, emitting floats
* make JSON formats able to encode None/NULL values, emitting nulls
=> Followups for JSON output formats

CHANGELOG
Update changelog for release v2.6.0
=> Update changelog for release v2.6.0
